version: '3.8'

services:
  # REST-сервис
  money-transfer-service:
    build: .
    container_name: money-transfer-service
    ports:
      - "5500:5500"
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5500/health" ]
      interval: 30s
      timeout: 3s
      retries: 3



networks:
  app-network:
    driver: bridge